import React from "react";
import { FormattedMessage } from "react-intl";

export default {
  _id: {},
  name: {
    presence: {
      message: <FormattedMessage id="SchemaSchoolForm.name.presence.message" />,
    },
    length: {
      minimum: 5,
      tooShort: <FormattedMessage id="SchemaSchoolForm.name.length.tooShort" />,
    },
  },
  unique_code: {},
  staff_count: {},
  staff_observations: {},
  type: {},
  student_diurnal_count: {},
  student_vespertine_count: {},
  student_nocturnal_count: {},
  student_full_count: {},
  kindergarten: {},
  elementary_1: {},
  elementary_2: {},
  highschool: {},
  technical: {},
  adult: {},
  "school_classe.kindergarten.manha.num_alunos_maior_turma": {},
  "school_classe.kindergarten.manha.num_turmas": {},
  "school_classe.kindergarten.manha.num_aluno": {},
  "school_classe.kindergarten.tarde.num_turmas": {},
  "school_classe.kindergarten.tarde.num_aluno": {},
  "school_classe.kindergarten.tarde.num_alunos_maior_turma": {},
  "school_classe.kindergarten.noite.num_turmas": {},
  "school_classe.kindergarten.noite.num_aluno": {},
  "school_classe.kindergarten.noite.num_alunos_maior_turma": {},
  "school_classe.kindergarten.integral.num_turmas": {},
  "school_classe.kindergarten.integral.num_aluno": {},
  "school_classe.kindergarten.integral.num_alunos_maior_turma": {},
  "school_classe.elementary_1.manha.num_turmas": {},
  "school_classe.elementary_1.manha.num_aluno": {},
  "school_classe.elementary_1.manha.num_alunos_maior_turma": {},
  "school_classe.elementary_1.tarde.num_turmas": {},
  "school_classe.elementary_1.tarde.num_aluno": {},
  "school_classe.elementary_1.tarde.num_alunos_maior_turma": {},
  "school_classe.elementary_1.noite.num_turmas": {},
  "school_classe.elementary_1.noite.num_aluno": {},
  "school_classe.elementary_1.noite.num_alunos_maior_turma": {},
  "school_classe.elementary_1.integral.num_turmas": {},
  "school_classe.elementary_1.integral.num_aluno": {},
  "school_classe.elementary_1.integral.num_alunos_maior_turma": {},
  "school_classe.elementary_2.manha.num_turmas": {},
  "school_classe.elementary_2.manha.num_aluno": {},
  "school_classe.elementary_2.manha.num_alunos_maior_turma": {},
  "school_classe.elementary_2.tarde.num_turmas": {},
  "school_classe.elementary_2.tarde.num_aluno": {},
  "school_classe.elementary_2.tarde.num_alunos_maior_turma": {},
  "school_classe.elementary_2.noite.num_turmas": {},
  "school_classe.elementary_2.noite.num_aluno": {},
  "school_classe.elementary_2.noite.num_alunos_maior_turma": {},
  "school_classe.elementary_2.integral.num_turmas": {},
  "school_classe.elementary_2.integral.num_aluno": {},
  "school_classe.elementary_2.integral.num_alunos_maior_turma": {},
  "school_classe.highschool.manha.num_turmas": {},
  "school_classe.highschool.manha.num_aluno": {},
  "school_classe.highschool.manha.num_alunos_maior_turma": {},
  "school_classe.highschool.tarde.num_turmas": {},
  "school_classe.highschool.tarde.num_aluno": {},
  "school_classe.highschool.tarde.num_alunos_maior_turma": {},
  "school_classe.highschool.noite.num_turmas": {},
  "school_classe.highschool.noite.num_aluno": {},
  "school_classe.highschool.noite.num_alunos_maior_turma": {},
  "school_classe.highschool.integral.num_turmas": {},
  "school_classe.highschool.integral.num_aluno": {},
  "school_classe.highschool.integral.num_alunos_maior_turma": {},
  "school_classe.technical.manha.num_turmas": {},
  "school_classe.technical.manha.num_aluno": {},
  "school_classe.technical.manha.num_alunos_maior_turma": {},
  "school_classe.technical.tarde.num_turmas": {},
  "school_classe.technical.tarde.num_aluno": {},
  "school_classe.technical.tarde.num_alunos_maior_turma": {},
  "school_classe.technical.noite.num_turmas": {},
  "school_classe.technical.noite.num_aluno": {},
  "school_classe.technical.noite.num_alunos_maior_turma": {},
  "school_classe.technical.integral.num_turmas": {},
  "school_classe.technical.integral.num_aluno": {},
  "school_classe.technical.integral.num_alunos_maior_turma": {},
  "school_classe.adult.manha.num_turmas": {},
  "school_classe.adult.manha.num_aluno": {},
  "school_classe.adult.manha.num_alunos_maior_turma": {},
  "school_classe.adult.tarde.num_turmas": {},
  "school_classe.adult.tarde.num_aluno": {},
  "school_classe.adult.tarde.num_alunos_maior_turma": {},
  "school_classe.adult.noite.num_turmas": {},
  "school_classe.adult.noite.num_aluno": {},
  "school_classe.adult.noite.num_alunos_maior_turma": {},
  "school_classe.adult.integral.num_turmas": {},
  "school_classe.adult.integral.num_aluno": {},
  "school_classe.adult.integral.num_alunos_maior_turma": {},
  regional: {},
  student_observations: {},
  location_type: {
    presence: {
      message: (
        <FormattedMessage id="SchemaSchoolForm.location_type.presence.message" />
      ),
    },
  },
  manager: {},
  observations: {},
  country_id: {},
  province_id: {},
  state_id: {},
  city_id: {},
  affiliation_id: {},
  country_name: {},
  province_name: {},
  affiliation_name: {},
  state_name: {},
  city_name: {},
  "school_infra.comp_teachers": {},
  "school_infra.comp_admins": {},
  "school_infra.comp_students": {},
  "school_infra.printers": {},
  "school_infra.rack": {},
  "school_infra.nobreak": {},
  "school_infra.switch": {},
  "school_infra.firewall": {},
  "school_infra.wifi": {},
  "school_infra.projector": {},
  "school_infra.charger": {},
  "school_infra.maker": {},
};
