version: "3.7"
services:
  frontend:
    build: .
    networks:
      - geos-network
    volumes:
      - "./:/app"
      - "node_modules:/app/node_modules"
    ports:
      - "8001:80"
    environment:
      - NODE_ENV=production

networks:
  geos-network:
volumes:
  node_modules:
